In [1]:
!pip install pandas openpyxl
!pip install pandas matplotlib seaborn scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: et_xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.7.0)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.12.2)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (1.10.0)
Requirement already satisfied: numpy>=1.21.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.25.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (22.0)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (9.4.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

# Cargar el archivo de Excel
file_path = "master_state.xlsx"  # Asegúrate de que el archivo esté en la misma ruta que tu notebook
sheet_name = "DataReg"  # Nombre de la pestaña que quieres cargar

# Leer el contenido de la pestaña "Data" en un DataFrame
df = pd.read_excel(file_path, sheet_name=sheet_name)

# Mostrar el contenido del DataFrame
df.head()
df_clean = df
df_clean.drop(columns=['URL'], inplace=True)

In [3]:
print(df_clean.head())

                                            Location          Meters  Price  \
0  Barquisimeto, Lara, Venezuela, Barquisimeto, B...   62 m² totales  14000
1  36 Y 37 Carrera 18, Barquisimeto 3001, Lara, V...  120 m² totales  23000
2  3pj2+6xg, Av. Libertador, Barquisimeto 3001, L...   81 m² totales  24000
3  2qp3+jjq, Cabudare 3023, Lara, Venezuela, El R...  150 m² totales  26000
4  2q86+xwf, Cabudare 3023, Lara, Venezuela, Cabu...   80 m² totales  25000

  Superficie total Superficie construida  Ambientes  Habitaciones  Baños  \
0            62 m²                 62 m²        1.0             2      1
1           120 m²                120 m²        1.0             3      1
2            81 m²                 81 m²        1.0             7      3
3           150 m²                150 m²        1.0             4      3
4            80 m²                 80 m²        1.0             3      2

   Estacionamientos  Alacenas  ...  Ascensor Cancha de básquetbol  \
0                 2       2.0  ...        No                   No
1                 1       1.0  ...        Sí                   No
2                 1       1.0  ...        No                   No
3                 5       1.0  ...        No                   No
4                 3       1.0  ...        No                   No

  Con cancha de fútbol Cancha de paddle Cancha de tenis  \
0                   No               No              No
1                   No               No              No
2                   No               No              No
3                   No               No              No
4                   No               No              No

  Con cancha polideportiva Salón de fiestas Sauna Heladera Amoblado
0                       Sí               Sí    No       No       Sí
1                       No               No    No       No       No
2                       No               No    No       No       Sí
3                       No               Sí    No       No       No
4                       No               No    No       No       Sí

[5 rows x 69 columns]

In [4]:
#Limpieza de la Data
df_clean['Meters'] = df_clean['Meters'].str.replace(' m² totales', '')
df_clean['Superficie total'] = df_clean['Superficie total'].str.replace(' m²', '')
df_clean['Superficie construida'] = df_clean['Superficie construida'].str.replace(' m²', '')
df_clean['Antigüedad'] = df_clean['Antigüedad'].str.replace(' años', '')
#Clean Numeric Fields
#df_clean['Price'] = df_clean['Price'].str.replace('.', '', regex=False)  # Eliminar los puntos
#df_clean['Price'] = df_clean['Price'].str.replace(',', '', regex=False)  # Eliminar las comas, si las hubiera
#df_clean['Price'] = df_clean['Price'].str.replace('[^\d.]', '', regex=True)  # Eliminar cualquier carácter no numérico
#df_clean['Price'] = pd.to_numeric(df_clean['Price'], errors='coerce')  # Convertir a numérico

df_clean.head()

,Location,Meters,Price,Superficie total,Superficie construida,Ambientes,Habitaciones,Baños,Estacionamientos,Alacenas,...,Ascensor,Cancha de básquetbol,Con cancha de fútbol,Cancha de paddle,Cancha de tenis,Con cancha polideportiva,Salón de fiestas,Sauna,Heladera,Amoblado
0,"Barquisimeto, Lara, Venezuela, Barquisimeto, B...",62,14000,62,62,1.0,2,1,2,2.0,...,No,No,No,No,No,Sí,Sí,No,No,Sí
1,"36 Y 37 Carrera 18, Barquisimeto 3001, Lara, V...",120,23000,120,120,1.0,3,1,1,1.0,...,Sí,No,No,No,No,No,No,No,No,No
2,"3pj2+6xg, Av. Libertador, Barquisimeto 3001, L...",81,24000,81,81,1.0,7,3,1,1.0,...,No,No,No,No,No,No,No,No,No,Sí
3,"2qp3+jjq, Cabudare 3023, Lara, Venezuela, El R...",150,26000,150,150,1.0,4,3,5,1.0,...,No,No,No,No,No,No,Sí,No,No,No
4,"2q86+xwf, Cabudare 3023, Lara, Venezuela, Cabu...",80,25000,80,80,1.0,3,2,3,1.0,...,No,No,No,No,No,No,No,No,No,Sí

In [5]:
import re
# Separar la columna "Location" utilizando la coma como delimitador
location_split = df_clean['Location'].str.split(',', expand=True)

# Asignar los valores separados a nuevas columnas en el DataFrame
for i in range(8):
    df_clean[f'Location_{i+1}'] = location_split[i]

# Función para limpiar y clasificar los valores
def classify_location(parts):
    country = ""
    state = ""
    plus_code = ""
    zone = ""
    city = ""

    for part in parts:
        if pd.isna(part):
            continue
        part = part.strip()
        if re.search(r'\bVenezuela\b', part, re.IGNORECASE):
            country = part
        elif re.search(r'\b(Lara|Miranda|Zulia|Caracas|Anzoátegui|Aragua|Bolívar)\b', part, re.IGNORECASE):
            state = part
        elif re.search(r'\b[2-9C-HJ-NP-TV-Z]{4}\+[2-9C-HJ-NP-TV-Z]{2,8}\b', part, re.IGNORECASE):
            plus_code = part
        elif city == "" and len(part.split()) == 1:
            city = part
        elif zone == "" and len(part.split()) > 1:
            zone = part

    return country, state, plus_code, city, zone

# Aplicar la función de clasificación a las columnas Location_1 a Location_8 y crear nuevas columnas
df_clean[['Pais', 'Estado', 'Plus Code', 'Ciudad', 'Zona']] = df_clean.apply(
    lambda row: pd.Series(classify_location(row[['Location_1', 'Location_2', 'Location_3', 'Location_4', 'Location_5', 'Location_6', 'Location_7', 'Location_8']])), axis=1
)

# Eliminar las columnas temporales de Location_1 a Location_8
df_clean.drop(columns=[f'Location_{i+1}' for i in range(8)], inplace=True)

# Mostrar las primeras filas del DataFrame para verificar
print(df_clean.head(30))

                                             Location Meters  Price  \
0   Barquisimeto, Lara, Venezuela, Barquisimeto, B...     62  14000
1   36 Y 37 Carrera 18, Barquisimeto 3001, Lara, V...    120  23000
2   3pj2+6xg, Av. Libertador, Barquisimeto 3001, L...     81  24000
3   2qp3+jjq, Cabudare 3023, Lara, Venezuela, El R...    150  26000
4   2q86+xwf, Cabudare 3023, Lara, Venezuela, Cabu...     80  25000
5   Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    100  11000
6   Barquisimeto, Lara, Zona Centro, 24-13160, Cen...    124  18500
7   2qj7+pj Cabudare, Lara, Venezuela, Cabudare, C...    108  11000
8   Barquisimeto, Lara, Venezuela, Cabudare, Cabud...    147  25000
9   Urb La Morenera, Carrera 5, Con C. C, Cabudare...    178  20000
10  Barquisimeto, Lara, Venezuela, Barquisimeto, B...    144   9000
11  La Piedad Norte, Cabudare, Lara, Venezuela, La...    268  19000
12  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    113  11500
13  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    157  26000
14  Barquisimeto, Lara, Venezuela, Barquisimeto, B...    250  25000
15  Barquisimeto, Lara, Venezuela, La Mata, Cabuda...    121  18900
16  Valle Hondo, Cabudare, Lara, Venezuela, Cabuda...    226  18000
17  2q7f+r22, Cabudare 3023, Lara, Venezuela, La P...    162  26000
18  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...     77  15000
19  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    120  12000
20  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    162  25000
21  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    167  18000
22  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...     73  20000
23  Cabudare, Lara, Venezuela, Cabudare, Cabudare,...    113  11500
24  Barquisimeto, Lara, Venezuela, La Mora, Cabuda...    129  24000
25  Cabudare, Lara, Venezuela, La Piedad, Cabudare...    157  26000
26  2pgv+w38, Av. 1, Cabudare 3023, Lara, Venezuel...    108  10500
27  2qg2+wv4, Cabudare 3023, Lara, Venezuela, Cabu...    147  25000
28  Barquisimeto, Lara, Venezuela, Barquisimeto, B...    120  23000
29  2q7h+72x, C. 4, Cabudare 3023, Lara, Venezuela...     73  20000

   Superficie total Superficie construida  Ambientes  Habitaciones  Baños  \
0                62                    62        1.0             2      1
1               120                   120        1.0             3      1
2                81                    81        1.0             7      3
3               150                   150        1.0             4      3
4                80                    80        1.0             3      2
5               100                   100        1.0             2      1
6               124                   124        5.0             2      1
7               108                   108        4.0             2      1
8               147                   147        2.0             3      2
9               178                   178        5.0             3      2
10              144                    70        1.0             2      2
11              268                   268        4.0             3      2
12              113                   113        1.0             3      1
13              157                   157        1.0             2      2
14              250                   250        0.0             3      2
15              121                    71        1.0             2      2
16              226                   226        2.0             3      2
17              162                   162        1.0             3      3
18               77                    77        1.0             3      2
19              120                   120        1.0             2      2
20              162                   162        1.0             2      2
21              167                   167        1.0             2      2
22               73                    73        1.0             2      3
23              113                   113        1.0             3      1
24              129                   129        1.0             4      3
25              157                   157        1.0             2      2
26              108                   108        1.0             2      1
27              147                   147        1.0             3      2
28              120                    12        1.0             3      1
29               73                   146        1.0             2      3

    Estacionamientos  Alacenas  ...  Con cancha polideportiva  \
0                  2       2.0  ...                        Sí
1                  1       1.0  ...                        No
2                  1       1.0  ...                        No
3                  5       1.0  ...                        No
4                  3       1.0  ...                        No
5                  2       1.0  ...                        No
6                  0       1.0  ...                        No
7                  1       3.0  ...                        No
8                  2       2.0  ...                        Sí
9                  5       1.0  ...                        No
10                 2       1.0  ...                        Sí
11                 4       1.0  ...                        No
12                 2       1.0  ...                        No
13                 1       1.0  ...                        No
14                 4       0.0  ...                        No
15                 2       1.0  ...                        No
16                 3       1.0  ...                        No
17                 2       1.0  ...                        No
18                 3       1.0  ...                        No
19                 2       1.0  ...                        No
20                 2       1.0  ...                        Sí
21                 2       1.0  ...                        No
22                 2       1.0  ...                        No
23                 2       1.0  ...                        No
24                 2       1.0  ...                        No
25                 1       1.0  ...                        Sí
26                 1       1.0  ...                        No
27                 2       1.0  ...                        No
28                 2       1.0  ...                        No
29                 2       1.0  ...                        No

   Salón de fiestas Sauna Heladera Amoblado       Pais Estado  \
0                Sí    No       No       Sí  Venezuela   Lara
1                No    No       No       No  Venezuela   Lara
2                No    No       No       Sí  Venezuela   Lara
3                Sí    No       No       No  Venezuela   Lara
4                No    No       No       Sí  Venezuela   Lara
5                No    No       No       No  Venezuela   Lara
6                No    No       No       No              Lara
7                No    No       No       No  Venezuela   Lara
8                Sí    No       No       No  Venezuela   Lara
9                No    No       No       No  Venezuela   Lara
10               Sí    No       No       No  Venezuela   Lara
11               No    No       No       No  Venezuela   Lara
12               No    No       No       No  Venezuela   Lara
13               No    No       No       No  Venezuela   Lara
14               No    No       No       No  Venezuela   Lara
15               No    No       No       No  Venezuela   Lara
16               No   NaN       No       No  Venezuela   Lara
17               Sí    Sí       No       No  Venezuela   Lara
18               Sí    No       No       No  Venezuela   Lara
19               No    No       No       No  Venezuela   Lara
20               No    No       No       Sí  Venezuela   Lara
21               No    No       No       No  Venezuela   Lara
22               No    No       No       No  Venezuela   Lara
23               No    No       No       No  Venezuela   Lara
24               No    No       No       No  Venezuela   Lara
25               Sí    No       No       No  Venezuela   Lara
26               No    No       No       No  Venezuela   Lara
27               No    No       No       Sí  Venezuela   Lara
28               No    No       No       No  Venezuela   Lara
29               No    No       No       No  Venezuela   Lara

           Plus Code        Ciudad                Zona
0                     Barquisimeto
1                     Barquisimeto  36 Y 37 Carrera 18
2           3pj2+6xg        Centro      Av. Libertador
3           2qp3+jjq      Cabudare       Cabudare 3023
4           2q86+xwf      Cabudare       Cabudare 3023
5                         Cabudare
6                     Barquisimeto         Zona Centro
7   2qj7+pj Cabudare      Cabudare
8                     Barquisimeto
9                         Cabudare     Urb La Morenera
10                    Barquisimeto
11                        Cabudare     La Piedad Norte
12                        Cabudare
13                        Cabudare
14                    Barquisimeto
15                    Barquisimeto             La Mata
16                        Cabudare         Valle Hondo
17          2q7f+r22      Cabudare       Cabudare 3023
18                        Cabudare
19                        Cabudare
20                        Cabudare
21                        Cabudare
22                        Cabudare
23                        Cabudare
24                    Barquisimeto             La Mora
25                        Cabudare           La Piedad
26          2pgv+w38      Cabudare               Av. 1
27          2qg2+wv4      Cabudare       Cabudare 3023
28                    Barquisimeto
29          2q7h+72x      Cabudare                C. 4

[30 rows x 74 columns]

In [6]:
# Obtener los valores únicos de las columnas 'Ciudad' y 'Zona'
unique_cities = df_clean['Ciudad'].unique()
unique_zones = df_clean['Zona'].unique()
unique_plus_code = df_clean['Plus Code'].unique()

# Mostrar los valores únicos de 'Ciudad'
print("Valores únicos de Ciudad:")
for city in unique_cities:
    print(city)

# Mostrar los valores únicos de 'Zona'
print("\nValores únicos de Zona:")
for zone in unique_zones:
    print(zone)
    
# Mostrar los valores únicos de 'Plus Code'
print("\nValores únicos de Plus Code:")
for code in unique_plus_code:
    print(code)

Valores únicos de Ciudad:
Barquisimeto
Centro
Cabudare
2
Tamaca
3001
Otros
Cubiro
Quíbor
Yacural
3023
Ribereña
Cambural
Almarriera
Duaca
Tarabana
Union
Laracasa
Patarata
Sarare
Trigaleña
Carora
Barici
Obelisco
Fundalara

Valores únicos de Zona:

36 Y 37 Carrera 18
Av. Libertador
Cabudare 3023
Zona Centro
Urb La Morenera
La Piedad Norte
La Mata
Valle Hondo
La Mora
La Piedad
Av. 1
C. 4
El Manzano 3001
Avenida Intercomunal Vía Sector La Piedad.
C. Principal La Mora
Autop. Barquisimeto - Acarigua
La Morenera
Urb. El Placer
Barquisimeto 3001
Calle 56
Carrera 9
C. 8
Avenida Libertador
Urbanización Hacienda Yucatán
Calle Guri
Las Mercedes
Carrera 12
Barquisimeto - Río Claro
Urbanización Chucho Briceño
El Cují
Urbanizacion El Trigal Abajo
Carretera El Placer
Urbanización La Puerta
Av. Ribereña
Carrera 5
Urbanización Valle Hondo
Av Intercomunal Barquisimeto Acarigua La Teura
Avenida La Montañita
Urbanización "las Mercedes"
Avenida Intercomunal Barquisimeto - Acarigua
Piedra Azul
Centro Comercial Terepaima Ii
Los Pinos
Granja San Miguel
Agua Viva 3050
Barquisimeto Metropolitan Area
Av. Bachue
Avenida Ribereña
Palavecino (Cabudare)
Calle Principal La Mora
La Ensenada
Zona Este Nueva Segovia
Tierras Del Sol
Villas Yara
Zona Norte El Cuji
Agua Viva
C. 2
Puertas del Sol
Calle 12
Avenida Intercomunal Barquisimeto - Duaca
Avenida Intercomunal Barquisimeto
Carrera 28
Urbanización Los Yabos
Avenida Ppal De La Piedad
El Tostao Sn
Carrera 33
Barquisimeto 3023
Autop. Cimarrón Andresote
Avenida El Placer
Calle 24 Entre Carreras 29 Y 30
El Trigal
Urb. Los Yabos
Calle 13
La Puerta
Calle El Centro
Carrera 27 & Calle 11
Av. Terepaima
Av El Placer
Santa Elena
C. Argentina
Calle 10 & Carrera 4
C. 32
C. D
C.c Centro Libertador Nivel Mezzanina
Barrio Union
Urbanización Caña Dorada
Avenida Vía Zanjón Colorado
C. 38
8 Vía La Montañita
Los Rastrojos
Av. La Montañita
Cabudare 3050
C. 3
2 Av. Intercomunal Barquisimeto - Acarigua
Calle San Rafael
Av Intercomunal Edif Darallo Piso Pb Local 3 Zona Centro
Urbanización Roca Del Valle 2
Urbanización Almariera
Santa Rosalia Sn
Urbanización Prados Del Golf Sn
Carrera 27
Tamaca 3001
Av. 3
C. 1
San José
Av. Bolivar. Urb. Atapaima Iii. Parroquia José Gregorio Bastidas
Av. Principal Sn
Zona Norte Tamaca
El Paraiso
La Montañita
Los Bucares
Urbanización Colinas De Santa Rosa
Zona Oeste
Av Intercomunal Barquisimeto Acarigua Los Cerezos
Bella Vista Plaza
Zona Norte Tamaca Roca Del Norte
Urbanización El Recreo
Avenida 2
El Recreo
El Placer
Av Ribereña Santa Fe
La Ribereña
La Piedad Sur
Av Intercomunal Barquisimeto Acarigua Roca Terra
Av Intercomunal Barquisimeto Acarigua La Hacienda
Chucho Briceño
Calle Los Pinos
Los Yabos
Av Ribereña Horizonte
El Cují 3001
Urbanizacion Rafael Caldera I
C. 5
Urbanizacion Patarata
Urbanizacion Ciudad Roca
Duaca 3025
Via El Trapiche
Veragacha 3001
Avenida Los Cerrajones
Los Naranjillos
Quíbor 3061
C. 9
Calle 33
Principal: Roca Del Norte Barquisimeto Cento
Troncal 4
Residencias Miño
Avenida Los Rastrojos
Av La Montañita Avenida La Montañita
Av. Intercomunal Barquisimeto - El Cují
Lomas de Tabure
Urb La Teura
Simón Planas
Av. 1 La Mata
Av. Vía Zanjón Colorado
Zona Norte Yucatan
La Lagunita
Urbanización Yucatán
Carrera 2
Carrera 1
Zona Este Colinas De Santa Rosa
Parroquia Catedral
Autopista Circunvalación Norte
Agua Viva El Roble
El Ujano
Avenida Tarabana
Calle 38
Calle 12 & Carrera 27
El Cercado
El Amanecer
Villa Amanecer
Calle 11
Urbanización Los Pinos
Calle 38 & Carrera 28
Calle Los Rastrojos
Calle 6
Zona Este 23 De Enero
Las Acacias
El Valle
Pueblo Nuevo
Carrera 6
Av. Edgar Mendoza
Av Ribereña Los Samanes
Prados Del Golf
Vista Verde
Villas Trabsider
Zona Este
Av Intercomunal Barquisimeto Acarigua Villa Roca
Av Intercomunal Barquisimeto Acarigua La Campiña
Urbanizacion Tierra Del Sol Iii
Calle 15
Villa Roca 2
Santa Eduvigis
Casa 22 C. 5a
Agua Viva Sn
Calle Suárez
Urb. Las Acacias
C. 28
El Trigal Sn
Av. Los Rastrojos
Avenida Intercomunal Vía A Duaca
Av 4 Cumbres Del Manzano. Sn
Carrera 25
Av. Intercomunal Barquisimeto - Acarigua
Avenida Principal
Las Mercedes Sn
La Morenera Sn
9069 C. C
C. 6
Valle Hondo 3001
Calle 8
Calle 7
Avenida Fuerzas Armadas
C. Aquilino Juárez
Valle Hondo Sn
Carrera 3
Urbanización Los Helechos Sn
Vía Sanjón Colorado
Urb. Los Pinos
Av Intercomunal Sn
El Manzano
Km 11 Via A Rio Claro Sn
Carrera 18 Sn
Urb. Valle Hondo
Carrera 24
San Vicente
3 Av. Terepaima
Del Este
Los Cardones
Trans. 6
C. 59
Av. Santa Barbara
3001 Código Postal 3001
Caminos De Tarabana
Villa Roca 1
Av. 4
C. 14 Italia
Fundalara Iii
Urbanización Los Cardones
Calle Las Trinitarias
Urb. El Obelisco
Carrera 31
La Rosaleda
C. 11
Urb. La Rosaleda
Tarabana Plaza
Avenida Negro Primero
Avenida Hernán Garmendia
Trapiche Villas
24 Y 25 Carrera 2
Avenida Nicolás Patino
Calle Union
Calle 59
Urbanización Las Trinitarias
El Placer Sn
Urbanizacion Fundalara
Zona Este Las Trinitarias
Zona Este Los Cardones
Av Ribereña Roca Del Valle
Carrera 13-c & Calle 59
Av. Hernán Garmendia
Zona Este La Rosaleda
Calle C
Calle 50
C. Canira
Concordia III
Calle 2
Urbanización La Rosaleda
Urbanización El Obelisco
Las Trinitarias
Calle 60
Carrera 13
Urbanización Santa Ines
Calle El Ujano
Avenida Morán
Calle Barquisimeto
Carrera 27 & Calle 10
Colegio Río Claro
21-33 C. 6
C. 10
Calle La Ruezga
Urbanización Del Este
Carrera 21 & Calle 15
Carrera 13-c & Calle 57
A Cabudare
Urbanización Valparaiso
Carrera 34
27 C. 5a
Carrera 16 & Calle 46
Carrera 17 & Calle 37
Urbanizacion Nueva Segovia
Calle Los Jabillos
Carrera 32 & Calle 26
Urb. Valparaiso
Carrera 13 & Calle 59
Carrera 13-c & Calle 55
C. Los Apamates
Urbanización La Concordia
Urbanización Roca Nostra

Valores únicos de Plus Code:

3pj2+6xg
2qp3+jjq
2q86+xwf
2qj7+pj Cabudare
2q7f+r22
2pgv+w38
2qg2+wv4
2q7h+72x
2mmq+fgx
2qh4+m34
2q5p+x5x
2pfx+6p7
2qp4+g98
2qgf+4gr
2q76+gmg
2q7g+6mv
2pqw+wrw
2pfx+9pv
7x5p+jh Rincón Hondo
2q6c+w53 Urb. Los Cerezos I
2qj7+89 Cabudare
2q3q+mw2
2qf3+2fx
3pj3+23h
3mc2+hfh
3p8g+wf6
3pj3+f56
3pp3+84g
3j4h+5x5
3pvf+q66
3p84+94r
2pfx+qmg
2pfv+5c2
2q83+f88 Urb. Petimora Ii
2ph4+mpc
3p9v+623
2qf2+gfm
2q7g+9g8
3jjx+3wf
3mc9+vq5
3jhx+cgw
2q92+979
37qp+wr El Placer
2pjx+c76
3pg3+jwh
2pgr+x2v
2q8g+2c2
2pgx+3wm
3mfw+c62
54xh+277
3m4j+x6q
2pwr+28h
2q83+qfw
2pf8+7h5
5m78+xrv
3q92+j7 Veragacha
3pcv+8gp
2qcc+xq9
3mf9+mcv
3mqr+4qv
3mg2+hj9
3pcw+x6h
2pjw+wv6
2pgx+779
2qm3+qqc
2pp9+8v
2qg6+892
2qf2+f3q
2q8c+qm5
2p8p+76
2pfq+r77
3mjg+5j9
2ph4+cwq
2pfx+8fm
2pcr+j38
2pcq+fr5
2q93+8h3
2qh6+g68
2qh6+gq6
3m9g+vfg
2qj3+7p8
2q3f+m8
2qm3+36
3p7f+96p
2q96+x94
2q7g+8gr
2pfm+x3j
3pfv+9m Barquisimeto
2pfx+g5m
2qf2+48j
2q2q+x3 Cabudare
2qfq+9p Cabudare
5mww+wv Tamaca
2qfc+wc8
2q95+p34 La Mora
2p7f+fh3
2qm3+c2w
3mcc+v7p
2q8g+4ch
2pgx+cm Cabudare
2qq5+7mj
2qc6+p4 Cabudare
2qh2+pmx
2pqf+cp Cabudare
3qvv+25 Cujisal
2q5f+wxm
2p9x+gcx
2qp7+93q
2phv+g7r
2qf3+c4
2ppc+679
2ppx+259
2qg5+5c7
2q8c+jf2
2q7f+6wm
2pgw+mxh Villa Roca 2
2pgx+vcf
2q82+jg
2qp2+f69
2qp4+95g
2qj7+6r8
2pgr+q48
2pgx+c8m
6p8w+5r Valle Hondo
2ppc+8q5
2pjv+pw7
3mc2+qww
2pfh+gq4
3jjq+7p
5pw2+84w
2pvx+p3 Cabudare
2phx+fj2
2pgp+q3g
2prw+4mr
2phw+xrh
2q8f+3r4
2q4j+wm3
2q9f+jv Cabudare
6p8w+5p Valle Hondo
2pfx+pcg
54xh+mj Agua Viva
2pfx+7f7
3p62+mx2
3m5p+35 Barquisimeto
2pgx+9p Cabudare
3mc3+549
2phg+xhh
5m4v+4q2
5pw2+r5 Tamaca
5m4v+3p9
4mvp+fqm
6m2w+758
2pcw+pxh
5pw3+8cx Urb.privada
3phh+w26 Conjunto Onix
7rqm+xxq
5pv3+54v
3qh4+g23
W9gh+v79
2pcx+xgr
2p9v+4hj
2q7h+69r Los Helechos
3mp2+g3p
5m6q+c85
2qf2+q8q
2qxh+977
2q8j+w84
2pgf+j2m
3phf+692
3mmh+75w
2qf4+m36
Xphm+w4 Cabudare
54xj+58 Agua Viva
3m8w+w6v
2pm9+mpv
3pp5+395
3p5h+3w6
54xh+qf Agua Viva
2pgm+7vm
2pcx+pc3
2pcv+5p6
2qq4+45f
2q84+wx5
4m7v+rr8
2q4h+65g
2qc7+w22
Xqr3+6w Cabudare
2pfw+pqj
2pqc+rc Cabudare
3p9m+2w Barquisimeto
3pcp+jh Barquisimeto
2pgr+6fv
2qc3+79f
2q5c+gx5
2pgx+8j Cabudare
2qf3+f3v
2ppw+4f6
2pqc+x2 Cabudare
2pqc+q8 Cabudare
2pvj+v2 Cabudare
2q3g+r54
2qjf+44 Cabudare
3mf2+g5f
2q8f+jv4
2qf7+v3w
2q7h+vmp
2q82+2j2
2pgp+5jc
2pqp+crc
2qm4+4jx
2q79+94m
2ppf+w3c
2p9x+xv Cabudare
2q5h+cff
2qh6+6rr
2q3g+pc4
2phq+xvw
2qh8+h28
3m5p+jcj
2qq8+m9 Cabudare
5m5p+4f El Cují
3jfx+qxr
3p83+gqp
3mj2+94x
2phq+9r7
2pfh+vj9
3mc2+3rh
3mm2+jrj
2qc6+238
2qg6+22r
2q3h+822
2qf6+m6 Cabudare
3pp2+wxg
2pjw+227
2pqx+gh5
3jmw+mqf
3pfv+pw Veragacha
2qf2+vfw
2pqx+frq
2phw+x94
3mc2+g3v
2qr6+35h
2phw+mc9 Planta Milazzo
2pcv+7rg
3m5p+3m Barquisimeto
3mg3+397
2pgh+9cw
2q9c+4fc
6p8w+qq Valle Hondo
3p8q+864
2pqx+j2x
2qh9+75w
2qp2+v3j
3jgx+4xf
6p8w+7r Valle Hondo
2phr+76q
2pmw+5c7
6p8w+3m Valle Hondo
2pgw+pmr
2prm+v8 Cabudare
2q8g+h9 Cabudare
2p7r+xc Cabudare
2phr+22v
3pm2+fph
2phw+mc9
2qg9+jgp
2pmx+qc6
3mjm+fj9
6p8w+fp Valle Hondo
2qf3+qm5
6p8w+3q Valle Hondo
2pgx+4h Cabudare
6p7w+fwj
2phx+9rw
3p4q+588
2q96+2xw
6p8w+4v Valle Hondo
3m92+hcp
3m92+wjw
3mh2+332
2q93+qc Cabudare
3m5p+47 Barquisimeto
2pgq+663
2qh2+5p3
3mp8+98g
3mjv+xcj
2pcw+6w4
3m44+2wc
Xqh9+xf Cabudare
2q4h+92j
3mcv+4c6
2pgc+58
3pm8+h5x
2qg4+77g
2pmg+x2
2q64+j69
3pg6+4w
2pqx+g9j
2pq8+wqr
2q78+xc2
Rv73+3r Gamelotal
3pm6+cr8
3m42+64h
3pfr+c3 Barquisimeto
2pp9+39 Cabudare
2pmp+9w8
2pcf+8m3
3pm5+56g
2q8c+53r
2qq3+23f
2pqx+fvh
3m5m+7p2
3m4m+mm8 Puente Macuto
2pmf+v6x
2pgq+g9c
3pff+j8h
2qg3+hvw
2q88+p4r
3ph6+h6f
3p9c+654 Santa Elena Park
3p74+w2f
3p8f+qx3
3pm3+82w
3pmg+pv Barquisimeto
2pv7+4q Cabudare
3mc2+j7x
3pm4+m3g
2pfw+c46
3mjv+724
2qh5+pj9
3mf3+44x
2pp9+gcg
2qf2+hf6
2pcm+wvg
2pv7+5r Cabudare
2ppx+r95
2ppw+vvm
2pgx+fp Cabudare
2ph9+ppw
2pmq+769
2q96+gvf
3p56+39w Plaza Barici
3p98+hf9
2qc4+vhh
3mf2+q79
2pjv+qq Cabudare
3m92+6qq
2pgw+7m2
3pph+727
3pcf+w79
3pgf+f4w
3pm9+g52
3p99+6jx
3p73+qvp
3mf2+gp9
3pgf+888
3ph3+frp
3ph3+jp3
2qf4+7w9
3p84+qx2
2jfx+78 El Manzano
3mg2+2hh
3pmj+qh
2prq+2xh
3mc5+ghm
3p8w+w6 Barquisimeto
3mg2+3jh
3mcj+8hq
2pjg+v83
2qc9+grq
2pmc+mxv
2pwr+8r4
3pj3+h3h
2p8x+rg2
2phr+59x
2pfj+75m
2qf8+qcw
2pp9+cq4
2qj7+525
2pq9+3qm
2q7c+mp6
3p63+qj7
2pfh+vgg
3pj3+wj9
3m35+pgv
2qc9+xpw
2qg4+9pg
3pj9+pmj
2prw+3cx
2qhg+8p Cabudare
3ph9+96x
3pvf+jcx
2pmh+j7c
2pp9+w8m
2q6j+7fg
2pq9+4v7
2q96+52w
2pjw+6hj
2pp7+2g Cabudare
2pmg+5qr
3p95+r75
3pfc+wwm
3pgc+3pw
3pff+993
2pmx+3g4
2pm9+gxv
2pvr+p2j

In [13]:
#Popular con "Casa" los campos seleccionados que sean Null
df_clean.fillna({"Tipo de casa": "No"}, inplace=True)

In [14]:
# Create a dictionary to store column names and null counts
# Contar los valores nulos en cada columna del DataFrame
null_counts = df_clean.isnull().sum()
null_counts_dict = {}
for col, count in null_counts.items():
    if count > 0:
        null_counts_dict[col] = count

# Print columns with null values and their counts
print("Columnas con valores nulos:")
for col, count in null_counts_dict.items():
    print(f"{col}: {count} null values")

Columnas con valores nulos:
Meters: 1 null values
Ambientes: 335 null values
Alacenas: 342 null values
Cantidad de pisos: 408 null values
Tipo de casa: 500 null values
Orientación: 319 null values
Gastos comunes: 347 null values
Alarma: 463 null values
Seguridad: 131 null values
Portón eléctrico: 284 null values
Tipo de seguridad: 1251 null values
Con barrio cerrado: 183 null values
Acceso controlado: 148 null values
Parrillera: 338 null values
Piscina: 354 null values
Armarios: 163 null values
Baño de visitas: 151 null values
Terraza: 370 null values
Comedor: 111 null values
Vestier: 355 null values
Estudio: 215 null values
Estar: 161 null values
Patio: 244 null values
Suite: 231 null values
Balcón: 375 null values
Ático: 393 null values
Jardín: 273 null values
Cocina: 100 null values
Cuarto de servicio: 345 null values
Sala de juego: 370 null values
Con cuarto de lavado: 161 null values
Área para desayunar: 172 null values
Acceso a internet: 167 null values
Aire acondicionado: 154 null values
Calefacción: 249 null values
TV por cable: 469 null values
Línea telefónica: 203 null values
Gas natural: 152 null values
Planta eléctrica: 259 null values
Con energia solar: 258 null values
Con conexión para lavarropas: 227 null values
Agua: 102 null values
Cisterna: 246 null values
Calentador a gas/ eléctrico: 212 null values
Chimenea: 280 null values
Gimnasio: 281 null values
Jacuzzi: 286 null values
Estacionamiento para visitantes: 190 null values
Área de cine: 272 null values
Área de juegos infantiles: 198 null values
Con área verde: 176 null values
Ascensor: 321 null values
Cancha de básquetbol: 307 null values
Con cancha de fútbol: 257 null values
Cancha de paddle: 277 null values
Cancha de tenis: 288 null values
Con cancha polideportiva: 252 null values
Salón de fiestas: 249 null values
Sauna: 300 null values
Heladera: 253 null values
Amoblado: 251 null values

In [ ]:
# Contar los valores nulos en cada columna del DataFrame
null_counts = df_clean.isnull().sum()

# Mostrar los resultados
print("Valores nulos en cada columna del DataFrame df_clean:")
print(null_counts)

In [ ]:
#Popular con "No" los campos seleccionados que sean Null
df_clean.fillna({"Location": "No", "Grill": "No", "Private Area": "No", 
                 "Garden": "No", "Pool": "No", "Electric Gate": "No", 
                 "Internet": "No", "Air Conditioner": "No", "Cable": "No", 
                 "Phone": "No", "Gas": "No", "Electric Plant": "No", 
                 "Solar Energy": "No"}, inplace=True)

In [ ]:
df_clean = df_clean.dropna(subset=["Meters", "Price", "Rooms", "Bathrooms"])
print(df_clean.shape)

In [ ]:
df_clean = df_clean.assign(Garage=df_clean["Garage"].fillna(0))

In [ ]:
unique_floors = df_clean["Floors"].unique()
print(unique_floors)

In [ ]:
df_clean["Floors"].replace(["Sí", "No"], 1, inplace=True)
df_clean["Floors"] = df_clean["Floors"].astype(object)  # Convert to object type
df_clean["Floors"] = df_clean["Floors"].replace("0", 1)  # Replace '0' with 1
df_clean["Floors"] = df_clean["Floors"].astype(int)  # Convert back to integer type

In [ ]:
unique_garage = df_clean["Garage"].unique()
print(unique_garage)

In [ ]:
df_clean["Garage"] = df_clean["Garage"].astype(object)  # Convert to object type
df_clean["Garage"] = df_clean["Garage"].replace("Casa", 0)  # Replace '0' with 1
df_clean["Garage"] = df_clean["Garage"].astype(int)  # Convert back to integer type

In [ ]:
# Realizar las conversiones de tipo de datos
df_clean['Meters'] = df_clean['Meters'].astype('float64')
df_clean['Rooms'] = df_clean['Rooms'].astype('int64')
df_clean['Bathrooms'] = df_clean['Bathrooms'].astype('int64')
df_clean['Floors'] = df_clean['Floors'].astype('int64')
df_clean['Garage'] = df_clean['Garage'].astype('int64')
df_clean['Antiquity'] = df_clean['Antiquity'].astype('int64')

In [ ]:
df_clean.info()

In [ ]:
df_clean["House Type"] = df_clean["House Type"].fillna("Casa")

In [ ]:
# Contar los valores nulos en cada columna del DataFrame
null_counts = df_clean.isnull().sum()

# Mostrar los resultados
print("Valores nulos en cada columna del DataFrame df_clean:")
print(null_counts)

In [ ]:
# Ver el tipo de cada campo
print(df_clean.dtypes)

In [ ]:
# Contar los valores nulos en cada columna del DataFrame
null_counts = df_clean.isnull().sum()

# Mostrar los resultados
print("Valores nulos en cada columna del DataFrame df_clean:")
print(null_counts)

In [ ]:
# Obtener estadísticas descriptivas del precio y otras variables numéricas
print(df_clean[['Price', 'Meters', 'Rooms', 'Bathrooms', 'Floors']].describe())

In [ ]:
#Calculate Average Price
average_price = df_clean['Price'].mean()
print(average_price)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [ ]:
# Supongamos que df es tu DataFrame
# df = pd.read_csv('tu_archivo.csv') # Carga tu DataFrame

# Vamos a enfocarnos en las columnas relevantes
numeric_columns = ['Meters', 'Price', 'Rooms', 'Bathrooms', 'Floors', 'Grill', 'Garage',
                   'Private Area', 'Garden', 'Pool', 'Antiquity', 'Electric Gate', 'House Type',
                   'Internet', 'Air Conditioner', 'Cable', 'Phone', 'Gas', 'Electric Plant',
                   'Solar Energy']

# Convertir las columnas a numéricas (si no lo están)
for column in numeric_columns:
    df_clean[column] = pd.to_numeric(df_clean[column], errors='coerce')

# Método de visualización con Boxplot
plt.figure(figsize=(15, 10))
df.boxplot(column=numeric_columns)
plt.xticks(rotation=90)
plt.title('Boxplot para detección de outliers')
plt.show()

# Método de los Cuartiles
Q1 = df_clean[numeric_columns].quantile(0.25)
Q3 = df_clean[numeric_columns].quantile(0.75)
IQR = Q3 - Q1

# Filtrar los outliers
outliers = ((df_clean[numeric_columns] < (Q1 - 1.5 * IQR)) | (df_clean[numeric_columns] > (Q3 + 1.5 * IQR)))
print("Outliers detectados por el método de los cuartiles:")
print(outliers.sum())

# Método del Z-Score
z_scores = np.abs(stats.zscore(df_clean[numeric_columns].dropna()))
outliers_z_score = (z_scores > 3)
print("Outliers detectados por el método del Z-Score:")
print(outliers_z_score.sum())

In [ ]:
import openpyxl
from openpyxl.styles import PatternFill
# Definir las columnas numéricas
numeric_columns = ['Meters', 'Price', 'Rooms', 'Bathrooms', 'Floors', 'Garage', 'Antiquity']  # Añade las columnas relevantes

# Calcular los cuartiles y el IQR
Q1 = df_clean[numeric_columns].quantile(0.25)
Q3 = df_clean[numeric_columns].quantile(0.75)
IQR = Q3 - Q1

# Identificar los outliers
outliers = df_clean[((df_clean[numeric_columns] < (Q1 - 1.5 * IQR)) | (df_clean[numeric_columns] > (Q3 + 1.5 * IQR))).any(axis=1)]

# Crear un archivo Excel con los registros de outliers
outliers.to_excel('outliers.xlsx', index=False)

# Cargar el archivo Excel
wb = openpyxl.load_workbook('outliers.xlsx')
ws = wb.active

# Definir un relleno para resaltar las celdas
highlight = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid")

# Resaltar las celdas que contienen outliers
for row in ws.iter_rows(min_row=2, max_row=ws.max_row, min_col=1, max_col=ws.max_column):
    for cell in row:
        col_idx = cell.column - 1
        if ws.cell(row=1, column=cell.column).value in numeric_columns:
            original_value = df_clean.loc[cell.row - 2, ws.cell(row=1, column=cell.column).value]
            if cell.value != original_value:
                cell.fill = highlight

# Guardar el archivo Excel con las celdas resaltadas
wb.save('outliers_highlighted.xlsx')

print(f"Se han resaltado las celdas con outliers en 'outliers_highlighted.xlsx'")

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
# Convertir las columnas relevantes a numéricas si no lo están ya
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Meters'] = pd.to_numeric(df['Meters'], errors='coerce')
df['Rooms'] = pd.to_numeric(df['Rooms'], errors='coerce')
df['Bathrooms'] = pd.to_numeric(df['Bathrooms'], errors='coerce')
df['Floors'] = pd.to_numeric(df['Floors'], errors='coerce')
df['Garage'] = pd.to_numeric(df['Garage'], errors='coerce')
df['Antiquity'] = pd.to_numeric(df['Antiquity'], errors='coerce')

# Calcular la correlación
correlation_matrix = df[['Price', 'Meters', 'Rooms', 'Bathrooms', 'Floors', 'Garage', 'Antiquity']].corr()

print(correlation_matrix)